### ISSUE TITLE
Rendre déploiement des branches plus sûr

### ISSUE THREAD

**Issue by egaillot** [betagouv/eva-orchestrateur#11]
Actuellement, il y a potentiellement moyen de faire des dégâts si on ne déploie pas une branche différente de `master` comme il faut (cf. avertissement dans `README.md`). Ça serait bien que cette opération soit moins risquée qu'actuellement.

Suggestion d'implémentation : faire en sorte que le `chemin_racine` et les noms des hôtes soit directement construit à partir des noms des branches déployées. Peut-être un hachage sur 8 caractères de la concaténation des noms de versions ?

**Comment by etienneCharignon** [comment]
Depuis que nous sommes passé chez Scalingo, cette issue n'est plus d'actualité il me semble.
